# Site wide configuration

title: "Kyungpyo Kim"
description: "Kyungpyo Kim's blog"
logo: 120x120.gif # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale: en
url: "https://kyungpyo-kim.github.io"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Kyungpyo Kim"
  email: "kyungpyo94@gmail.com"
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

# Tagging
# ref: http://tech.kakao.com/2016/07/07/tech-blog-story/
# _tags 디렉토리 안에 있는 파일 목록을 수집해서 
# /tags/...로 서비스되도록 HTML 파일을 생성하라는 설정
# collections:
#   tags:
#     output: true
#     permalink: /tags/:path/
# defaults:
#   - scope: 
#       path: ''
#       type: tags
#     values:
#       layout: tag

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
